In [1]:
import numpy as np
import pandas as pd

Considere os arrays numpy X, y abaixo:

In [2]:
from sklearn.datasets import load_iris

X = load_iris().data
y = load_iris().target

In [3]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

__Exercício 1:__ Crie um dataframe df do pandas a partir de X, y.

Primeiro, concatene os arrays numpy. Na sequência transforme o array final para um dataframe. Altere o nome das colunas para 'X1', 'X2', 'X3', 'X4' e 'target'.

In [5]:
print(X.shape)

(150, 4)


In [6]:
print(y.shape)

(150,)


In [7]:
array_final = np.c_[X,y]
print(array_final)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

In [8]:
print(array_final.shape)

(150, 5)


In [9]:
df = pd.DataFrame(array_final)
print(df)

       0    1    2    3    4
0    5.1  3.5  1.4  0.2  0.0
1    4.9  3.0  1.4  0.2  0.0
2    4.7  3.2  1.3  0.2  0.0
3    4.6  3.1  1.5  0.2  0.0
4    5.0  3.6  1.4  0.2  0.0
..   ...  ...  ...  ...  ...
145  6.7  3.0  5.2  2.3  2.0
146  6.3  2.5  5.0  1.9  2.0
147  6.5  3.0  5.2  2.0  2.0
148  6.2  3.4  5.4  2.3  2.0
149  5.9  3.0  5.1  1.8  2.0

[150 rows x 5 columns]


In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df.rename({0 :'X1', 1: 'X2', 2:'X3', 3:'X4', 4:'target'}, axis=1, inplace=True)

In [12]:
print(df)

      X1   X2   X3   X4  target
0    5.1  3.5  1.4  0.2     0.0
1    4.9  3.0  1.4  0.2     0.0
2    4.7  3.2  1.3  0.2     0.0
3    4.6  3.1  1.5  0.2     0.0
4    5.0  3.6  1.4  0.2     0.0
..   ...  ...  ...  ...     ...
145  6.7  3.0  5.2  2.3     2.0
146  6.3  2.5  5.0  1.9     2.0
147  6.5  3.0  5.2  2.0     2.0
148  6.2  3.4  5.4  2.3     2.0
149  5.9  3.0  5.1  1.8     2.0

[150 rows x 5 columns]


__Exercício 2:__ Usando o df criano no exercício 1, calcule qual a média da variável 'X2', para cada valor de target. Dica: Use a função groupby no dataframe df para resolver.

In [13]:
df.groupby('target').agg({"X2":'mean'})

X2
target       
0.0     3.428
1.0     2.770
2.0     2.974

__Exercício 3:__ Construa um dicionário mapeando os valores:
        
        0 - 'A'
        
        1 - 'B'
        
        2 - 'C'
        
Usando a função map, crie uma coluna nova no dataframe df chamada 'target_2' com o mapeamento feito. Dica: Use a função map como visto em aula.

In [14]:
dicio = {0:'A', 1:'B', 2:'C'}
print(dicio)

{0: 'A', 1: 'B', 2: 'C'}


In [15]:
df['target_2'] = 'NaN'

In [16]:
df.head()

X1   X2   X3   X4  target target_2
0  5.1  3.5  1.4  0.2     0.0      NaN
1  4.9  3.0  1.4  0.2     0.0      NaN
2  4.7  3.2  1.3  0.2     0.0      NaN
3  4.6  3.1  1.5  0.2     0.0      NaN
4  5.0  3.6  1.4  0.2     0.0      NaN

In [17]:
df.target_2 = df.target.map(dicio)
df.head()

X1   X2   X3   X4  target target_2
0  5.1  3.5  1.4  0.2     0.0        A
1  4.9  3.0  1.4  0.2     0.0        A
2  4.7  3.2  1.3  0.2     0.0        A
3  4.6  3.1  1.5  0.2     0.0        A
4  5.0  3.6  1.4  0.2     0.0        A

__Exercício 4:__ 


4.1: Filtre o dataframe df onde X1 é maior do que 6 __ou__ target é diferente de 2 e chame-o de df1. Dica: usar os filtros e os operadores vistos em aula;

4.2: Filtre os primeiros 15 índices do dataframe df e chame-o de df2;

4.3: Transformando os dataframes df1 e df2 para arrays. Multiplique df1 pelo transposto de df2 (use a função que calcula transposta de matriz) e printe o resultado final. Lembre-se de dropar a coluna target_2 de cada um dos dataframes antes de fazer a mutliplicação.

4.1

In [18]:
df1 = df[(df.X1 > 6) | (df.target != 2)]


In [19]:
print(df1)

      X1   X2   X3   X4  target target_2
0    5.1  3.5  1.4  0.2     0.0        A
1    4.9  3.0  1.4  0.2     0.0        A
2    4.7  3.2  1.3  0.2     0.0        A
3    4.6  3.1  1.5  0.2     0.0        A
4    5.0  3.6  1.4  0.2     0.0        A
..   ...  ...  ...  ...     ...      ...
144  6.7  3.3  5.7  2.5     2.0        C
145  6.7  3.0  5.2  2.3     2.0        C
146  6.3  2.5  5.0  1.9     2.0        C
147  6.5  3.0  5.2  2.0     2.0        C
148  6.2  3.4  5.4  2.3     2.0        C

[141 rows x 6 columns]


In [20]:
df1.head()

X1   X2   X3   X4  target target_2
0  5.1  3.5  1.4  0.2     0.0        A
1  4.9  3.0  1.4  0.2     0.0        A
2  4.7  3.2  1.3  0.2     0.0        A
3  4.6  3.1  1.5  0.2     0.0        A
4  5.0  3.6  1.4  0.2     0.0        A

4.2

In [21]:
df2 = df1[:16]
df2.head(16)

X1   X2   X3   X4  target target_2
0   5.1  3.5  1.4  0.2     0.0        A
1   4.9  3.0  1.4  0.2     0.0        A
2   4.7  3.2  1.3  0.2     0.0        A
3   4.6  3.1  1.5  0.2     0.0        A
4   5.0  3.6  1.4  0.2     0.0        A
5   5.4  3.9  1.7  0.4     0.0        A
6   4.6  3.4  1.4  0.3     0.0        A
7   5.0  3.4  1.5  0.2     0.0        A
8   4.4  2.9  1.4  0.2     0.0        A
9   4.9  3.1  1.5  0.1     0.0        A
10  5.4  3.7  1.5  0.2     0.0        A
11  4.8  3.4  1.6  0.2     0.0        A
12  4.8  3.0  1.4  0.1     0.0        A
13  4.3  3.0  1.1  0.1     0.0        A
14  5.8  4.0  1.2  0.2     0.0        A
15  5.7  4.4  1.5  0.4     0.0        A

4.3

In [22]:
df1.head()

X1   X2   X3   X4  target target_2
0  5.1  3.5  1.4  0.2     0.0        A
1  4.9  3.0  1.4  0.2     0.0        A
2  4.7  3.2  1.3  0.2     0.0        A
3  4.6  3.1  1.5  0.2     0.0        A
4  5.0  3.6  1.4  0.2     0.0        A

In [23]:
np1_array = df1.to_numpy()

display(np1_array)

print(type(np1_array))

array([[5.1, 3.5, 1.4, 0.2, 0.0, 'A'],
       [4.9, 3.0, 1.4, 0.2, 0.0, 'A'],
       [4.7, 3.2, 1.3, 0.2, 0.0, 'A'],
       [4.6, 3.1, 1.5, 0.2, 0.0, 'A'],
       [5.0, 3.6, 1.4, 0.2, 0.0, 'A'],
       [5.4, 3.9, 1.7, 0.4, 0.0, 'A'],
       [4.6, 3.4, 1.4, 0.3, 0.0, 'A'],
       [5.0, 3.4, 1.5, 0.2, 0.0, 'A'],
       [4.4, 2.9, 1.4, 0.2, 0.0, 'A'],
       [4.9, 3.1, 1.5, 0.1, 0.0, 'A'],
       [5.4, 3.7, 1.5, 0.2, 0.0, 'A'],
       [4.8, 3.4, 1.6, 0.2, 0.0, 'A'],
       [4.8, 3.0, 1.4, 0.1, 0.0, 'A'],
       [4.3, 3.0, 1.1, 0.1, 0.0, 'A'],
       [5.8, 4.0, 1.2, 0.2, 0.0, 'A'],
       [5.7, 4.4, 1.5, 0.4, 0.0, 'A'],
       [5.4, 3.9, 1.3, 0.4, 0.0, 'A'],
       [5.1, 3.5, 1.4, 0.3, 0.0, 'A'],
       [5.7, 3.8, 1.7, 0.3, 0.0, 'A'],
       [5.1, 3.8, 1.5, 0.3, 0.0, 'A'],
       [5.4, 3.4, 1.7, 0.2, 0.0, 'A'],
       [5.1, 3.7, 1.5, 0.4, 0.0, 'A'],
       [4.6, 3.6, 1.0, 0.2, 0.0, 'A'],
       [5.1, 3.3, 1.7, 0.5, 0.0, 'A'],
       [4.8, 3.4, 1.9, 0.2, 0.0, 'A'],
       [5.0, 3.0, 1.6, 0.

<class 'numpy.ndarray'>


In [24]:
df1_limpo = np1_array[:, :5]
print(df1_limpo)

[[5.1 3.5 1.4 0.2 0.0]
 [4.9 3.0 1.4 0.2 0.0]
 [4.7 3.2 1.3 0.2 0.0]
 [4.6 3.1 1.5 0.2 0.0]
 [5.0 3.6 1.4 0.2 0.0]
 [5.4 3.9 1.7 0.4 0.0]
 [4.6 3.4 1.4 0.3 0.0]
 [5.0 3.4 1.5 0.2 0.0]
 [4.4 2.9 1.4 0.2 0.0]
 [4.9 3.1 1.5 0.1 0.0]
 [5.4 3.7 1.5 0.2 0.0]
 [4.8 3.4 1.6 0.2 0.0]
 [4.8 3.0 1.4 0.1 0.0]
 [4.3 3.0 1.1 0.1 0.0]
 [5.8 4.0 1.2 0.2 0.0]
 [5.7 4.4 1.5 0.4 0.0]
 [5.4 3.9 1.3 0.4 0.0]
 [5.1 3.5 1.4 0.3 0.0]
 [5.7 3.8 1.7 0.3 0.0]
 [5.1 3.8 1.5 0.3 0.0]
 [5.4 3.4 1.7 0.2 0.0]
 [5.1 3.7 1.5 0.4 0.0]
 [4.6 3.6 1.0 0.2 0.0]
 [5.1 3.3 1.7 0.5 0.0]
 [4.8 3.4 1.9 0.2 0.0]
 [5.0 3.0 1.6 0.2 0.0]
 [5.0 3.4 1.6 0.4 0.0]
 [5.2 3.5 1.5 0.2 0.0]
 [5.2 3.4 1.4 0.2 0.0]
 [4.7 3.2 1.6 0.2 0.0]
 [4.8 3.1 1.6 0.2 0.0]
 [5.4 3.4 1.5 0.4 0.0]
 [5.2 4.1 1.5 0.1 0.0]
 [5.5 4.2 1.4 0.2 0.0]
 [4.9 3.1 1.5 0.2 0.0]
 [5.0 3.2 1.2 0.2 0.0]
 [5.5 3.5 1.3 0.2 0.0]
 [4.9 3.6 1.4 0.1 0.0]
 [4.4 3.0 1.3 0.2 0.0]
 [5.1 3.4 1.5 0.2 0.0]
 [5.0 3.5 1.3 0.3 0.0]
 [4.5 2.3 1.3 0.3 0.0]
 [4.4 3.2 1.3 0.2 0.0]
 [5.0 3.5 1

In [25]:
np2_array = df2.to_numpy()

display(np2_array)

print(type(np2_array))

array([[5.1, 3.5, 1.4, 0.2, 0.0, 'A'],
       [4.9, 3.0, 1.4, 0.2, 0.0, 'A'],
       [4.7, 3.2, 1.3, 0.2, 0.0, 'A'],
       [4.6, 3.1, 1.5, 0.2, 0.0, 'A'],
       [5.0, 3.6, 1.4, 0.2, 0.0, 'A'],
       [5.4, 3.9, 1.7, 0.4, 0.0, 'A'],
       [4.6, 3.4, 1.4, 0.3, 0.0, 'A'],
       [5.0, 3.4, 1.5, 0.2, 0.0, 'A'],
       [4.4, 2.9, 1.4, 0.2, 0.0, 'A'],
       [4.9, 3.1, 1.5, 0.1, 0.0, 'A'],
       [5.4, 3.7, 1.5, 0.2, 0.0, 'A'],
       [4.8, 3.4, 1.6, 0.2, 0.0, 'A'],
       [4.8, 3.0, 1.4, 0.1, 0.0, 'A'],
       [4.3, 3.0, 1.1, 0.1, 0.0, 'A'],
       [5.8, 4.0, 1.2, 0.2, 0.0, 'A'],
       [5.7, 4.4, 1.5, 0.4, 0.0, 'A']], dtype=object)

<class 'numpy.ndarray'>


In [26]:
df2_limpo = np2_array[:, :5]
print(df2_limpo)

[[5.1 3.5 1.4 0.2 0.0]
 [4.9 3.0 1.4 0.2 0.0]
 [4.7 3.2 1.3 0.2 0.0]
 [4.6 3.1 1.5 0.2 0.0]
 [5.0 3.6 1.4 0.2 0.0]
 [5.4 3.9 1.7 0.4 0.0]
 [4.6 3.4 1.4 0.3 0.0]
 [5.0 3.4 1.5 0.2 0.0]
 [4.4 2.9 1.4 0.2 0.0]
 [4.9 3.1 1.5 0.1 0.0]
 [5.4 3.7 1.5 0.2 0.0]
 [4.8 3.4 1.6 0.2 0.0]
 [4.8 3.0 1.4 0.1 0.0]
 [4.3 3.0 1.1 0.1 0.0]
 [5.8 4.0 1.2 0.2 0.0]
 [5.7 4.4 1.5 0.4 0.0]]


In [27]:
df2_limpo.T

array([[5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7],
       [3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3.0,
        3.0, 4.0, 4.4],
       [1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
        1.1, 1.2, 1.5],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
        0.1, 0.2, 0.4],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0]], dtype=object)

In [28]:
multi_df1_df2 = np.dot(df1_limpo, df2_limpo.T)

print(multi_df1_df2)

[[40.26 37.489999999999995 37.03 ... 33.989999999999995 45.3 46.65]
 [37.489999999999995 35.010000000000005 34.49 ... 31.63 42.14 43.31]
 [37.03 34.49 34.06 ... 31.26 41.660000000000004 42.900000000000006]
 ...
 [48.26 45.75000000000001 44.49 ... 40.28 52.92 55.169999999999995]
 [51.33 48.53 47.31 ... 42.870000000000005 56.339999999999996
  58.85000000000001]
 [51.54 48.6 47.50000000000001 ... 43.029999999999994 56.50000000000001
  59.32000000000001]]


__Exercício 5:__ 
    
5.1: Crie uma função que receba um  número inteiro positivo N e retorne um array 0, 1, ..., N. Dica: Use as funções que vimos para criação de arrays;
    
5.2: Crie uma função que receba um array [0,1, .., N] e retorne o mesmo array, só que com os números em posições aleatórias. Dica: use a função que vimos em aula que faz escolhas aleatórias SEM reposição;

5.3: Crie uma função que receba um número inteiro positivo N. Essa função deve retornar um array de tamanho N, cujos valores são números inteiros entre 0 e N-1 e pode haver repetição desses números.

In [29]:
import random

In [30]:
def array_formado(n):
    while True:
        try:
            if n <= 0:
        except Exception:
            print('Valor inválido. Tente novamente.')
        else:
            array_formado = np.arange (0, n, 1)
            print ('O array formado é:')
            return(array_formado)    

IndentationError: expected an indented block (<ipython-input-30-2b63f62ae008>, line 5)

In [ ]:
def array_embaralhado(n):
    while True:
        try:
            if n <= 0:
        except Exception:
            print('Valor inválido. Tente novamente.')
        else:
            array_recebido = np.random.randint (0, 100, size=n)
            print(f'O array recebido é: {array_recebido}.')
            array_embaralhado = np.random.sample(array_recebido)
            print('O array formado é:')
            return(array_embaralhado)  

In [ ]:
def array_tamanhodefinido(n):
    while True:
        try:
            if n <= 0:
        except Exception:
            print('Valor inválido. Tente novamente.')
        else:
            array_formado = np.random.choice (0, num-1, size = n)
            print(f'O array formado é: ')
            return array_formado 
                 

__Exercício 6:__ Construa uma função divide_dados:
        
        - recebe um array X de dimensões quaisquer (n,k) e um parâmetro p entre 0 e 1.
        - divide o array X em duas partes disjuntas de forma aleatória. Ou seja, crie dois novos arrays, X1 e X2,
        onde a dimensão de linhas de X1 somada com a dimensão de linhas de X2 deve ser igual a dimensão de linhas de X.
        - interpretando p como percentual, o tamanho de X1 deve ser p*100% do número de linhas de X; enquanto X2 deve ser o resto.
        - retorne esses dois arrays.
        
       

In [ ]:
def divide_dados (n,k,p):
    mat = linha = []
    for i in range(0, n, 1):
        for j in range(0, k, 1):
            elementos = random.randint(0,100)
            linha.append(elementos)
            mat.append(linha)

    X = np.array(mat)
    print(f'Array X: {X}.')

    y=np.array_split(X,2)
    X1 = y[0]
    X2 = y[1]

    print(f'Array X1: {X1}.')
    print(f'Array X2: {X2}.')

    x1 = X1.ndim
    x2 = X2.ndim

    print(f'Tamanho X1: {x1}')
    print(f'Tamanho X2: {x2}')

    array_x1 = np.random.normal(loc = 0, scale = 1, size = x1)
    array_x2 = np.random.normal(loc = 0, scale = 1, size = x2)
    
return (array_x1, array_x2)